services:
  spring-boot:
    restart: 'on-failure'
    build:
      dockerfile: Dockerfile
    container_name: 'back-server'
    ports:
      - '8080:8080'
    depends_on:
      - redis
  redis:
    restart: 'on-failure'
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
