/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Blackfish.glb 
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhead-seabream-a-schlegelii-865614b9b83e412f8d7e7aa0a1757124
Title: クロダイ チヌ ♂ Blackhead Seabream, A. schlegelii.
*/

import React, { useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { TweenMax, Power1 } from "gsap";

export function Blackfish(props) {
  const { nodes, materials } = useGLTF("/Blackfish.glb");

  const fishGroupRef = useRef();
  const fishMovement = useRef({
    speed: 0.02,
    targetPosition: new THREE.Vector3(), // Target position for smooth movement
  });

  useEffect(() => {
    // Set initial target position
    updateTargetPosition();
  }, []);

  useFrame((state, delta) => {
    if (fishGroupRef.current) {
      // 부드러운 이동
      fishGroupRef.current.position.lerp(
        fishMovement.current.targetPosition,
        delta * 0.5
      );

      // 부드러운 회전
      const lookAtVector = new THREE.Vector3()
        .copy(fishMovement.current.targetPosition)
        .sub(fishGroupRef.current.position);
      fishGroupRef.current.rotation.y = Math.atan2(
        lookAtVector.x,
        lookAtVector.z
      );

      // 일정 시간이 지날 때마다 새로운 목표 위치 설정
      if (state.clock.elapsedTime % 5 < delta) {
        updateTargetPosition();
      }
    }
  });

  const updateTargetPosition = () => {
    fishMovement.current.targetPosition.set(
      Math.random() * 40 - 20,
      Math.random() * 2 - 10,
      Math.random() * 40 - 20
    );
    TweenMax.to(fishMovement.current.targetPosition, 12, {
      x: Math.random() * 40 - 20,
      y: Math.random() * 90 - 35,
      z: Math.random() * 40 - 20,
      ease: Power1.easeInOut,
    });
  };

  return (
    <group {...props} ref={fishGroupRef} dispose={null}>
      <group rotation={[0.365, -1.01, -2.883]} scale={0.35}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["Q11246-1all-1-futa"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Blackfish.glb");
