/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Blackfish.glb 
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhead-seabream-a-schlegelii-865614b9b83e412f8d7e7aa0a1757124
Title: クロダイ チヌ ♂ Blackhead Seabream, A. schlegelii.
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Blackfish(props) {
  const { nodes, materials } = useGLTF("/Blackfish.glb");
  console.log(nodes);
  console.log(materials);
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.365, -1.01, -2.883]} scale={0.5}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Q11246-1all-1-body_tex0"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials["Q11246-1all-1-body_tex1"]}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials["Q11246-1all-1-body_tex2"]}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["Q11246-1all-1-futa"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Blackfish.glb");
