/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 coral.glb 
Author: Sandra_s (https://sketchfab.com/Sandra_sm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coral-c26e47859f0945d69a4e2944ee80b995
Title: Coral
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Coral(props) {
  const { nodes, materials } = useGLTF("/coral.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pCylinder23_Redd_0.geometry}
        material={materials.Redd}
      />
    </group>
  );
}

useGLTF.preload("/coral.glb");
