/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\public\\FishTank.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function FishTank(props) {
  const { nodes, materials } = useGLTF("/FishTank.glb");

  materials["Material.005"].roughness = 0;
  materials["Material.005"].ior = 1;
  materials["Material.005"].iridescenceIOR = 0;
  materials["Material.005"].flatShading = false;
  materials["Material.005"].iridescenceThicknessRange = [];

  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Sphere.geometry} material={materials["Material.005"]} />
    </group>
  );
}

useGLTF.preload("/FishTank.glb");
