/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\CornPlant.glb
*/

import React, { useEffect, useRef } from "react";
import { Object3D } from "three";
import { GoldFish } from "./GoldFish.jsx";
import { Clownfish } from "./Clownfish.jsx";
import { Stonefish } from "./Stonefish.jsx";
import { SeaBreamfish } from "./SeaBreamfish.jsx";
import { Blackfish } from "./Blackfish.jsx";
import { useFrame } from "@react-three/fiber";
import { Boid, Flock } from "./Flock.js";
import { Tilefish } from "./Tilefish.jsx";
import { MegiFish } from "./MegiFish.jsx";
import { IngFish } from "./IngFish.jsx";

export function FishGroup(props) {

  const { clownExist, stoneExist, breamExist, blackExist, tileExist, megiExist, ingExist } = props;

  return (
    <>
      <group {...props}>
        {clownExist && <Clownfish></Clownfish>}
        {stoneExist && <Stonefish></Stonefish>}
        {breamExist && <SeaBreamfish></SeaBreamfish>}
        {blackExist && <Blackfish></Blackfish>}
        {tileExist && <Tilefish></Tilefish>}
        {megiExist && <MegiFish></MegiFish>}
        {ingExist && <IngFish></IngFish>}
      </group>
    </>
  );
}
