/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 megi.glb 
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/amur-catfish-silurus-asotus-62643dfb143a48ca97bdb09cd075e680
Title: ナマズ （マナマズ）♀ Amur Catfish, Silurus asotus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
export function MegiFish(props) {
  const { nodes, materials } = useGLTF("/megi.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-2.843, -0.035, 1.868]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials["Q1113-W10-1all-2_tex0"]} />
        <mesh geometry={nodes.Object_7.geometry} material={materials["Q1113-W10-1all-2_tex0"]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials["Q1113-W10-1all-2_tex0"]} />
        <mesh geometry={nodes.Object_9.geometry} material={materials["Q1113-W10-1all-2_tex0"]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials["Q1113-W10-1all-2_tex0"]} />
        <mesh geometry={nodes.Object_11.geometry} material={materials["Q1113-W10-1all-2_tex0"]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials["Q1113-W10-1all-2_tex1"]} />
        <mesh geometry={nodes.Object_13.geometry} material={materials["Q1113-W10-1all-2_tex1"]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials["Q1113-W10-1all-2_tex1"]} />
        <mesh geometry={nodes.Object_15.geometry} material={materials["Q1113-W10-1all-2_tex1"]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials["Q1113-W10-1all-2_tex1"]} />
        <mesh geometry={nodes.Object_17.geometry} material={materials["Q1113-W10-1all-2_tex1"]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials["Q1113-W10-1all-2_tex2"]} />
        <mesh geometry={nodes.Object_19.geometry} material={materials["Q1113-W10-1all-2_tex2"]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials["Q1113-W10-1all-2_tex2"]} />
        <mesh geometry={nodes.Object_21.geometry} material={materials["Q1113-W10-1all-2_tex2"]} />
        <mesh geometry={nodes.Object_22.geometry} material={materials["Q1113-W10-1all-2_tex2"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/megi.glb");
