/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SeaBreamfish.glb 
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crimson-sea-bream-evynnis-tumifrons-592532a2390d48bfb6b4cd2f30f75aca
Title: チダイ Crimson Sea Bream, Evynnis tumifrons
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SeaBreamfish(props) {
  const { nodes, materials } = useGLTF("/SeaBreamfish.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.024, -0.379, -2.866]} scale={0.5}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Q11679-1all-2_tex0"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Q11679-1all-2_tex0"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Q11679-1all-2_tex0"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Q11679-1all-2_tex0"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Q11679-1all-2_tex0"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Q11679-1all-2_tex0"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Q11679-1all-2_tex1"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Q11679-1all-2_tex1"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Q11679-1all-2_tex1"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Q11679-1all-2_tex1"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Q11679-1all-2_tex1"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/SeaBreamfish.glb");
