/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shell.glb 
Author: blenderboom (https://sketchfab.com/blenderboom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sea-shell-742a5f4a7bc84abe8d0c645cdb411cc8
Title: Sea shell
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shell(props) {
  const { nodes, materials } = useGLTF("/shell.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.BB_13_001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/shell.glb");
