/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shell2.glb 
Author: Meshfinder (https://sketchfab.com/meshfinder)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sea-shell-photogrammetry-f68ff40bd67b4b62b2f131d91e724728
Title: Sea Shell (Photogrammetry)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shell2(props) {
  const { nodes, materials } = useGLTF("/shell2.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Shell}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shell2.glb");
