/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 starfish.glb 
Author: yingxu1999 (https://sketchfab.com/yingxu199998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starfish-6b5629bc0d954e10a068d1a0c87fe795
Title: Starfish
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Starfish(props) {
  const { nodes, materials } = useGLTF("/starfish.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Default}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/starfish.glb");
