/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Stonefish.glb 
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/barred-knifejaw-oplegnathus-fasciatus-ba36863e2c8a4f4fb21f31be423f28aa
Title: イシダイ Barred Knifejaw, Oplegnathus fasciatus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Stonefish(props) {
  const { nodes, materials } = useGLTF("/Stonefish.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.846, 1.379, 0.192]} scale={0.5}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Q11783-1all_tex0"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials["Q11783-1all_tex1"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Stonefish.glb");
