/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 underwater.glb 
Author: Susannetjotta (https://sketchfab.com/susannetjotta)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/underwater-scene-7622d8f9409e457f824f48014408041e
Title: Underwater Scene
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Underwater(props) {
  const { nodes, materials } = useGLTF("/underwater.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <group position={[-0.088, 0.4, 1.677]} scale={1}>
            <mesh geometry={nodes.Large_rock_05_Assets_Texture_0.geometry} material={materials.Assets_Texture} scale={0.6} />
            <mesh geometry={nodes.Large_rock_05_Sand_Texture_0.geometry} material={materials.Sand_Texture} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/underwater.glb");
